/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tudua.dictionary;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.Clip;
import javax.sound.sampled.AudioSystem;
import javax.swing.JFrame;
import com.sun.speech.freetts.VoiceManager; 
import java.awt.Component;
import java.awt.Font;
import java.awt.PopupMenu;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.Action;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author AnhThu_dbez
 */
public class MyFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyFrame
     */
    public DefaultListModel defaultListModel;
    
    public MyFrame()throws Exception {
        initComponents();
        showWord.setVisible(false);
        backButton.setVisible(false);
        editPanel.setVisible(false);
        showallPanel.setVisible(false);
        paraPanel.setVisible(false);
        workingPanel3.setVisible(false);
        workingPanel4.setVisible(false);
        defaultListModel = new DefaultListModel();
        wordList.setListData(Dictionary.toArray());
        
        //wordList
        wordList.setSelectedIndex(0);
        word_target.setText(Dictionary.getWord(0).getWord_target().trim());
        word_type.setText(Dictionary.getWord(0).getWord_type().trim());
        word_pronoun.setText(Dictionary.getWord(0).getSpell().trim());
        explainArea.setText(Dictionary.getWord(0).getWord_explain().trim());
        //wordList
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public void speech(String text) {
        VoiceManager voiceManager = VoiceManager.getInstance();
        com.sun.speech.freetts.Voice syntheticVoice = voiceManager.getVoice("kevin16");
        syntheticVoice.allocate();
        syntheticVoice.speak(text);
        syntheticVoice.deallocate();
    }
    
    public ArrayList<Word> ListsuggestWord(String s) {
        ArrayList<Word> resWord = new ArrayList<Word>();
        resWord = DictionaryManagement.dictionaryLookup(s);
        return resWord;
    }
    
    public String[] suggestWord(String s) {
        ArrayList<Word> resWord = new ArrayList<Word>();
        resWord = DictionaryManagement.dictionaryLookup(s);
        
        String[] resWordString = new String[resWord.size()];
        for (int i = 0; i < resWord.size(); i++) {
            resWordString[i] = resWord.get(i).getWord_target();
        }
        
        //javax.swing.JList<String> resList = new JList<>();
        //resList.setListData(resWordString);
        
        //System.out.println("hihi");
        
        /*
        for (int i = 0; i < resWord.size(); i++) {
            javax.swing.JMenuItem suggest = new javax.swing.JMenuItem(resWord.get(i).getWord_target());
            suggest.setAutoscrolls(true);
            suggest.setFont(Font.decode("Arial BOLD 14"));
            
            
            
            suggest.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    
                    /*
                    word_target1.setText(resMenu.get);
                    word_type1.setText(Dictionary.getWord(word_th).getWord_type().trim());
                    word_pronoun1.setText(Dictionary.getWord(word_th).getSpell().trim());
                    explainArea1.setText(Dictionary.getWord(word_th).getWord_explain().trim());
                    
                    showWord.setVisible(true);
                    backButton.setVisible(true);
                    menuPanel.setVisible(false);
                }
            });
            
            
            resMenu.add(suggest);
        }*/
        return resWordString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suggestPopup = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        popupPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        popupList = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        constantPanel = new javax.swing.JPanel();
        nameDictionary = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        workingPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JLabel();
        wordTarget = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        menuPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        showallButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        paraButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showWord = new javax.swing.JPanel();
        word_target1 = new javax.swing.JLabel();
        word_pronoun1 = new javax.swing.JLabel();
        word_type1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        explainArea1 = new javax.swing.JTextArea();
        playSound1 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        editdataPanel = new javax.swing.JTabbedPane();
        addPanel = new javax.swing.JPanel();
        addTarget = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addExplain = new javax.swing.JTextArea();
        addType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addSpell = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        removePanel = new javax.swing.JPanel();
        deleteDic = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        editWPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        addType1 = new javax.swing.JTextField();
        addSpell1 = new javax.swing.JTextField();
        addTarget1 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        addExplain1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        showallPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        wordList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        word_target = new javax.swing.JLabel();
        word_type = new javax.swing.JLabel();
        word_pronoun = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        explainArea = new javax.swing.JTextArea();
        playSound = new javax.swing.JLabel();
        paraPanel = new javax.swing.JPanel();
        paraTarget = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        paraExplain = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        workingPanel3 = new javax.swing.JPanel();
        workingPanel4 = new javax.swing.JPanel();

        suggestPopup.setAutoscrolls(true);
        suggestPopup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        suggestPopup.setLabel("");
        suggestPopup.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                suggestPopupAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        suggestPopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestPopupMouseClicked(evt);
            }
        });
        suggestPopup.getAccessibleContext().setAccessibleName("");

        jDialog1.setBackground(new java.awt.Color(199, 236, 238));
        jDialog1.setLocation(new java.awt.Point(500, 300));
        jDialog1.setPreferredSize(new java.awt.Dimension(200, 200));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(120, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 112, 147));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÀNH CÔNG");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        popupList.setFont(new java.awt.Font("VNI-Vari", 0, 14)); // NOI18N
        popupList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        popupList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        popupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popupListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(popupList);

        javax.swing.GroupLayout popupPanelLayout = new javax.swing.GroupLayout(popupPanel);
        popupPanel.setLayout(popupPanelLayout);
        popupPanelLayout.setHorizontalGroup(
            popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
            .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );
        popupPanelLayout.setVerticalGroup(
            popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        constantPanel.setBackground(new java.awt.Color(34, 112, 147));
        constantPanel.setPreferredSize(new java.awt.Dimension(603, 72));
        constantPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameDictionary.setFont(new java.awt.Font("VNI-Revue", 1, 18)); // NOI18N
        nameDictionary.setForeground(new java.awt.Color(255, 255, 255));
        nameDictionary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_books_48px_1.png"))); // NOI18N
        nameDictionary.setText("TUDUA DICTIONARY");
        nameDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        constantPanel.add(nameDictionary, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 13, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_back_50px.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        constantPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        getContentPane().add(constantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 603, -1));

        workingPanel.setBackground(new java.awt.Color(199, 236, 238));
        workingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/Untitled-1.png"))); // NOI18N
        searchButton.setLabelFor(wordTarget);
        searchButton.setToolTipText("");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        searchButton.setMaximumSize(new java.awt.Dimension(25, 25));
        searchButton.setMinimumSize(new java.awt.Dimension(25, 25));
        searchButton.setPreferredSize(new java.awt.Dimension(50, 50));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 30, 30));

        wordTarget.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        wordTarget.setForeground(new java.awt.Color(209, 204, 192));
        wordTarget.setText("Search any words here");
        wordTarget.setBorder(null);
        wordTarget.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                wordTargetFocusLost(evt);
            }
        });
        wordTarget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordTargetMouseClicked(evt);
            }
        });
        wordTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wordTargetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wordTargetKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordTargetKeyTyped(evt);
            }
        });
        searchPanel.add(wordTarget, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 11, 484, 31));
        searchPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 583, 11));

        workingPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 583, -1));

        menuPanel.setBackground(new java.awt.Color(199, 236, 238));

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_settings_50px.png"))); // NOI18N
        editButton.setText("Edit Database");
        editButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        editButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        newButton.setBackground(new java.awt.Color(255, 255, 255));
        newButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_new_50px_1.png"))); // NOI18N
        newButton.setText("New Features");
        newButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        newButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newButton.setPreferredSize(new java.awt.Dimension(179, 59));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        showallButton.setBackground(new java.awt.Color(255, 255, 255));
        showallButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        showallButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_microsoft_word_50px.png"))); // NOI18N
        showallButton.setText("Show All Words");
        showallButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        showallButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_exit_50px.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exitButton.setLabel("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        paraButton.setBackground(new java.awt.Color(255, 255, 255));
        paraButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        paraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_align_left_50px.png"))); // NOI18N
        paraButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        paraButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paraButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        paraButton.setLabel("Paragraph Translate");
        paraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paraButtonMouseClicked(evt);
            }
        });
        paraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("@ EST 2020 - University of Engineering and Technology, Ha Noi, Viet Nam");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("By TUDUA Team");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showallButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paraButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(paraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showallButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        workingPanel.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 400));

        showWord.setBackground(new java.awt.Color(255, 255, 255));
        showWord.setPreferredSize(new java.awt.Dimension(583, 340));

        word_target1.setFont(new java.awt.Font("SVN-Gotham Light", 0, 24)); // NOI18N
        word_target1.setText("target");

        word_pronoun1.setBackground(new java.awt.Color(255, 255, 255));
        word_pronoun1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        word_pronoun1.setForeground(new java.awt.Color(34, 112, 147));
        word_pronoun1.setText("pronoun");

        word_type1.setBackground(new java.awt.Color(255, 255, 255));
        word_type1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        word_type1.setForeground(new java.awt.Color(34, 91, 114));
        word_type1.setText("type");

        explainArea1.setColumns(20);
        explainArea1.setFont(new java.awt.Font("SVN-Gotham Light", 0, 18)); // NOI18N
        explainArea1.setRows(5);
        explainArea1.setFocusable(false);
        jScrollPane5.setViewportView(explainArea1);

        playSound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_audio_32px.png"))); // NOI18N
        playSound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playSound1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showWordLayout = new javax.swing.GroupLayout(showWord);
        showWord.setLayout(showWordLayout);
        showWordLayout.setHorizontalGroup(
            showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showWordLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showWordLayout.createSequentialGroup()
                        .addComponent(word_type1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(showWordLayout.createSequentialGroup()
                        .addGroup(showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, showWordLayout.createSequentialGroup()
                                .addGroup(showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(word_target1)
                                    .addComponent(word_pronoun1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playSound1)))
                        .addGap(40, 40, 40))))
        );
        showWordLayout.setVerticalGroup(
            showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showWordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(showWordLayout.createSequentialGroup()
                        .addComponent(word_target1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(word_pronoun1))
                    .addGroup(showWordLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(playSound1)))
                .addGap(58, 58, 58)
                .addComponent(word_type1)
                .addGap(86, 86, 86)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        workingPanel.add(showWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 583, 340));

        getContentPane().add(workingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 603, -1));

        editPanel.setBackground(new java.awt.Color(199, 236, 238));
        editPanel.setPreferredSize(new java.awt.Dimension(603, 480));

        editdataPanel.setBackground(new java.awt.Color(255, 255, 255));
        editdataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editdataPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        editdataPanel.setFont(new java.awt.Font("VNI-Vari", 0, 16)); // NOI18N
        editdataPanel.setName(""); // NOI18N
        editdataPanel.setPreferredSize(new java.awt.Dimension(603, 480));

        addPanel.setBackground(new java.awt.Color(199, 236, 238));
        addPanel.setName(""); // NOI18N

        addTarget.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addTarget.setForeground(new java.awt.Color(149, 165, 166));
        addTarget.setText("Nhập từ bạn muốn thêm");
        addTarget.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTargetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addTargetFocusLost(evt);
            }
        });
        addTarget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTargetMouseClicked(evt);
            }
        });

        addExplain.setColumns(20);
        addExplain.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addExplain.setForeground(new java.awt.Color(149, 165, 166));
        addExplain.setRows(5);
        addExplain.setText("Nghĩa tiếng Việt là:");
        addExplain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addExplainFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addExplainFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(addExplain);

        addType.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addType.setForeground(new java.awt.Color(149, 165, 166));
        addType.setText("Nhập từ loại");
        addType.setPreferredSize(new java.awt.Dimension(149, 22));
        addType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addTypeFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addSpell.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addSpell.setForeground(new java.awt.Color(149, 165, 166));
        addSpell.setText("Nhập phát âm");
        addSpell.setPreferredSize(new java.awt.Dimension(149, 22));
        addSpell.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addSpellFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addSpellFocusLost(evt);
            }
        });

        jLabel5.setText(" ");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                        .addComponent(addTarget)
                        .addComponent(addSpell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addType, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(addSpell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editdataPanel.addTab("Add Word", new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_add_50px.png")), addPanel, ""); // NOI18N

        removePanel.setBackground(new java.awt.Color(199, 236, 238));

        deleteDic.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        deleteDic.setForeground(new java.awt.Color(149, 165, 166));
        deleteDic.setText("Nhập từ bạn muốn xóa");
        deleteDic.setPreferredSize(new java.awt.Dimension(216, 28));
        deleteDic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deleteDicFocusGained(evt);
            }
        });
        deleteDic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteDicMouseClicked(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        deleteButton.setText("REMOVE");
        deleteButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel6.setText(" ");

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(deleteDic, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteDic, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editdataPanel.addTab("Remove Word", new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_delete_50px_1.png")), removePanel); // NOI18N

        editWPanel.setBackground(new java.awt.Color(199, 236, 238));
        editWPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editWPanelMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("VNI-Vari", 0, 18)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        addType1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addType1.setForeground(new java.awt.Color(149, 165, 166));
        addType1.setText("Nhập từ loại mới");
        addType1.setPreferredSize(new java.awt.Dimension(149, 22));
        addType1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addType1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addType1FocusLost(evt);
            }
        });

        addSpell1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addSpell1.setForeground(new java.awt.Color(149, 165, 166));
        addSpell1.setText("Nhập phát âm mới");
        addSpell1.setPreferredSize(new java.awt.Dimension(149, 22));
        addSpell1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addSpell1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addSpell1FocusLost(evt);
            }
        });

        addTarget1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addTarget1.setForeground(new java.awt.Color(149, 165, 166));
        addTarget1.setText("Nhập từ bạn muốn sửa");
        addTarget1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTarget1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addTarget1FocusLost(evt);
            }
        });
        addTarget1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTarget1MouseClicked(evt);
            }
        });
        addTarget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTarget1ActionPerformed(evt);
            }
        });

        addExplain1.setColumns(20);
        addExplain1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        addExplain1.setForeground(new java.awt.Color(149, 165, 166));
        addExplain1.setRows(5);
        addExplain1.setText("Nghĩa tiếng Việt mới:");
        addExplain1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addExplain1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addExplain1FocusLost(evt);
            }
        });
        jScrollPane8.setViewportView(addExplain1);

        jLabel9.setText(" ");

        javax.swing.GroupLayout editWPanelLayout = new javax.swing.GroupLayout(editWPanel);
        editWPanel.setLayout(editWPanelLayout);
        editWPanelLayout.setHorizontalGroup(
            editWPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editWPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(editWPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(editWPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(addTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addType1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSpell1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        editWPanelLayout.setVerticalGroup(
            editWPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTarget1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addType1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(addSpell1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editdataPanel.addTab("Edit Word", new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_edit_50px.png")), editWPanel); // NOI18N

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editdataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editdataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        editdataPanel.getAccessibleContext().setAccessibleName("tab2");

        getContentPane().add(editPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, -1, 480));

        showallPanel.setBackground(new java.awt.Color(199, 236, 238));
        showallPanel.setPreferredSize(new java.awt.Dimension(603, 480));
        showallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        wordList.setBackground(new java.awt.Color(199, 236, 238));
        wordList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wordList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        wordList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        wordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordListMouseClicked(evt);
            }
        });
        wordList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wordListKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wordListKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(wordList);

        showallPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 160, 480));

        jPanel1.setBackground(new java.awt.Color(34, 91, 114));
        jPanel1.setPreferredSize(new java.awt.Dimension(603, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("VNI-Vari", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_list_26px_2.png"))); // NOI18N
        jLabel2.setText("Definition");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        showallPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, 450, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        word_target.setFont(new java.awt.Font("SVN-Gotham Light", 0, 24)); // NOI18N
        word_target.setText("target");

        word_type.setBackground(new java.awt.Color(255, 255, 255));
        word_type.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        word_type.setForeground(new java.awt.Color(34, 91, 114));
        word_type.setText("type");

        word_pronoun.setBackground(new java.awt.Color(255, 255, 255));
        word_pronoun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        word_pronoun.setForeground(new java.awt.Color(34, 112, 147));
        word_pronoun.setText("pronoun");

        explainArea.setColumns(20);
        explainArea.setFont(new java.awt.Font("SVN-Gotham Light", 0, 18)); // NOI18N
        explainArea.setRows(5);
        explainArea.setFocusable(false);
        jScrollPane4.setViewportView(explainArea);

        playSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tudua/dictionary/ButtonIcon/icons8_audio_32px.png"))); // NOI18N
        playSound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playSoundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(word_type)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(word_target)
                                    .addComponent(word_pronoun))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(playSound)))
                        .addGap(40, 40, 40))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(word_target)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(word_pronoun))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(playSound)))
                .addGap(58, 58, 58)
                .addComponent(word_type)
                .addGap(86, 86, 86)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showallPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 470, 430));

        getContentPane().add(showallPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 603, 480));

        paraPanel.setBackground(new java.awt.Color(199, 236, 238));
        paraPanel.setPreferredSize(new java.awt.Dimension(603, 470));

        paraTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraTargetActionPerformed(evt);
            }
        });
        paraTarget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paraTargetKeyPressed(evt);
            }
        });

        paraExplain.setColumns(20);
        paraExplain.setRows(5);
        jScrollPane7.setViewportView(paraExplain);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setText("Nhập văn bản:");

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setText("Nghĩa Tiếng Việt là:");

        javax.swing.GroupLayout paraPanelLayout = new javax.swing.GroupLayout(paraPanel);
        paraPanel.setLayout(paraPanelLayout);
        paraPanelLayout.setHorizontalGroup(
            paraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paraPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(paraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(paraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(paraTarget)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paraPanelLayout.setVerticalGroup(
            paraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paraPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paraTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(paraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 603, 480));

        workingPanel3.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout workingPanel3Layout = new javax.swing.GroupLayout(workingPanel3);
        workingPanel3.setLayout(workingPanel3Layout);
        workingPanel3Layout.setHorizontalGroup(
            workingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        workingPanel3Layout.setVerticalGroup(
            workingPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(workingPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, -1, -1));

        workingPanel4.setBackground(new java.awt.Color(199, 236, 238));

        javax.swing.GroupLayout workingPanel4Layout = new javax.swing.GroupLayout(workingPanel4);
        workingPanel4.setLayout(workingPanel4Layout);
        workingPanel4Layout.setHorizontalGroup(
            workingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        workingPanel4Layout.setVerticalGroup(
            workingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(workingPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newButtonActionPerformed

    private void wordTargetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordTargetKeyPressed
        // TODO add your handling code here:
        //wordTarget.setText(wordTarget.getText().toLowerCase());
        
      /*  if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            String explain = DictionaryManagement.lookUpWord(wordTarget.getText().toLowerCase().trim(), Dictionary.getArrayWord(), 0, Dictionary.getArrayWord().size() - 1);
            //System.out.println(explain);
            word_target1.setText(wordTarget.getText());
            word_type1.setText("");
            word_pronoun1.setText("");
            explainArea1.setText(explain);
                
            showWord.setVisible(true);
            backButton.setVisible(true);
            menuPanel.setVisible(false);
            suggestPopup.setVisible(false); 
        } */
        
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {    
            String explain;
            try {
                explain = DictionaryCommandLine1.connect.getExplain(wordTarget.getText().trim());
                word_target1.setText(wordTarget.getText());
                word_type1.setText("");
                word_pronoun1.setText("");
                explainArea1.setText(explain);
                
                showWord.setVisible(true);
                backButton.setVisible(true);
                menuPanel.setVisible(false);
                suggestPopup.setVisible(false); 
            } catch (SQLException ex) {
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 
        
        /*
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            try {
                String explain = Connect.getExplain(wordTarget.getText().trim());
                word_target1.setText(wordTarget.getText());
                explainArea1.setText(explain);
                
                showWord.setVisible(true);
                backButton.setVisible(true);
                menuPanel.setVisible(false);
                suggestPopup.setVisible(false); 
            } catch (SQLException ex) {
                word_target1.setText(wordTarget.getText());
                word_type1.setText("KHÔNG TÌM THẤY TỪ");
                word_pronoun1.setText("");
                explainArea1.setText("");
                
                showWord.setVisible(true);
                backButton.setVisible(true);
                menuPanel.setVisible(false);
                suggestPopup.setVisible(false); 
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            System.out.println("hehiehi");
        }
        */
        
    }//GEN-LAST:event_wordTargetKeyPressed

    private void wordTargetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordTargetMouseClicked
        // TODO add your handling code here:
        //if (wordTarget.getText().equals("Search any words here")) wordTarget.setText("");
        wordTarget.setText("");
        wordTarget.setForeground(Color.BLACK);
    }//GEN-LAST:event_wordTargetMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        /*
        String target = wordTarget.getText().trim();
            String explain = DictionaryManagement.dictionaryLookup(target);
            showTarget.setText(target);
            showExplain.setText(explain);
            showWord.setVisible(true);
            backButton.setVisible(true);
            menuPanel.setVisible(false);
        */
    }//GEN-LAST:event_searchButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        showWord.setVisible(false);
        editPanel.setVisible(false);
        showallPanel.setVisible(false);
        paraPanel.setVisible(false);
        workingPanel.setVisible(true);
        menuPanel.setVisible(true);
        if (workingPanel.isVisible()) backButton.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        workingPanel.setVisible(false);
        editPanel.setVisible(true);
        backButton.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void showallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallButtonActionPerformed
        // TODO add your handling code here:
        wordList.setListData(Dictionary.toArray());
        workingPanel.setVisible(false);
        showallPanel.setVisible(true);
        //workingPanel2.setVerifyInputWhenFocusTarget(true);
        backButton.setVisible(true);
        
    }//GEN-LAST:event_showallButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void paraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paraButtonActionPerformed

    private void wordTargetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordTargetKeyTyped
        // TODO add your handling code here:
        if (wordTarget.getText().equals("Search any words here")) {
        char target = evt.getKeyChar();
        //wordTarget.setText(wordTarget.getText().toLowerCase());
        wordTarget.setText("");
        wordTarget.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_wordTargetKeyTyped

    private void wordTargetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordTargetKeyReleased
        // TODO add your handling code here:
        if (!wordTarget.getText().trim().equals("")) {
        if (evt.getKeyCode() != KeyEvent.VK_DOWN && evt.getKeyCode() != KeyEvent.VK_UP && evt.getKeyCode() != KeyEvent.VK_ENTER){
            wordTarget.setText(wordTarget.getText().toLowerCase());
            popupList.setListData(suggestWord(wordTarget.getText().toLowerCase().trim()));
            if (suggestWord(wordTarget.getText().toLowerCase().trim()).length == 0) {
                suggestPopup.setVisible(false);
                return;
            }
            suggestPopup.add(popupPanel);
            suggestPopup.show(wordTarget, wordTarget.getX(), wordTarget.getY() + wordTarget.getHeight());
            wordTarget.requestFocus(true);   
        } }
    }//GEN-LAST:event_wordTargetKeyReleased

    private void suggestPopupAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_suggestPopupAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_suggestPopupAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel5.setText(DictionaryManagement.dictionaryInsert(addTarget.getText().trim(), addExplain.getText(), addType.getText(), addSpell.getText()));
        //jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteDicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDicMouseClicked
        // TODO add your handling code here:
        jLabel6.setText(" ");
        deleteDic.setText("");
    }//GEN-LAST:event_deleteDicMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            // TODO add your handling code here:
            jLabel6.setText(DictionaryManagement.dictionaryDelete(deleteDic.getText()));
            //jDialog1.setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addTargetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTargetFocusLost
        // TODO add your handling code here:
        if (!addTarget.isFocusOwner() && addTarget.getText().trim().equals("")) {
            addTarget.setText("Nhập từ bạn muốn thêm");
            if (addTarget.getText().equals("Nhập từ bạn muốn thêm")) addTarget.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addTargetFocusLost

    private void addTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTypeFocusLost
        // TODO add your handling code here:
        if (!addType.isFocusOwner() && addType.getText().trim().equals("")) {
            addType.setText("Nhập từ loại");
            if (addType.getText().equals("Nhập từ loại")) addType.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addTypeFocusLost

    private void addSpellFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSpellFocusLost
        // TODO add your handling code here:
        if (!addSpell.isFocusOwner() && addSpell.getText().trim().equals("")) {
            addSpell.setText("Nhập phát âm");
            if (addSpell.getText().equals("Nhập phát âm")) addSpell.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addSpellFocusLost

    private void wordTargetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_wordTargetFocusLost
        // TODO add your handling code here:
        if (!wordTarget.isFocusOwner() && wordTarget.getText().equals("")) {
            wordTarget.setText("Search any words here");
            if (wordTarget.getText().equals("Search any words here")) wordTarget.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_wordTargetFocusLost

    private void addExplainFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addExplainFocusLost
        // TODO add your handling code here:
        if (!addExplain.isFocusOwner() && addExplain.getText().trim().equals("")) {
            addExplain.setText("Nghĩa tiếng Việt là:");
            if (addExplain.getText().equals("Nghĩa tiếng Việt là:")) addExplain.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addExplainFocusLost

    private void addTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTypeFocusGained
        // TODO add your handling code here:
        if (addType.getText().equals("Nhập từ loại")) addType.setText("");
        addType.setForeground(Color.BLACK);
    }//GEN-LAST:event_addTypeFocusGained

    private void addTargetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTargetFocusGained
        // TODO add your handling code here:
        if (addTarget.getText().equals("Nhập từ bạn muốn thêm")) addTarget.setText("");
        addTarget.setForeground(Color.BLACK);
    }//GEN-LAST:event_addTargetFocusGained

    private void addSpellFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSpellFocusGained
        // TODO add your handling code here:
        if (addSpell.getText().equals("Nhập phát âm")) addSpell.setText("");
        addSpell.setForeground(Color.BLACK);
    }//GEN-LAST:event_addSpellFocusGained

    private void addExplainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addExplainFocusGained
        // TODO add your handling code here:
        if (addExplain.getText().equals("Nghĩa tiếng Việt là:")) addExplain.setText("");
        addExplain.setForeground(Color.BLACK);
    }//GEN-LAST:event_addExplainFocusGained

    private void deleteDicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deleteDicFocusGained
        // TODO add your handling code here:
        if (deleteDic.getText().equals("Nhập từ bạn muốn xóa")) deleteDic.setText("");
        deleteDic.setForeground(Color.BLACK);
    }//GEN-LAST:event_deleteDicFocusGained

    private void wordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordListMouseClicked
        // TODO add your handling code here:
        String word = wordList.getSelectedValue();
        int word_th = wordList.getSelectedIndex();
        word_target.setText(word);
        word_type.setText(Dictionary.getWord(word_th).getWord_type().trim());
        word_pronoun.setText(Dictionary.getWord(word_th).getSpell().trim());
        explainArea.setText(Dictionary.getWord(word_th).getWord_explain().trim());
    }//GEN-LAST:event_wordListMouseClicked

    private void wordListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordListKeyTyped
        // TODO add your handling code here:
        String word = wordList.getSelectedValue();
        int word_th = wordList.getSelectedIndex();
        word_target.setText(word);
        word_type.setText(Dictionary.getWord(word_th).getWord_type().trim());
        word_pronoun.setText(Dictionary.getWord(word_th).getSpell().trim());
        explainArea.setText(Dictionary.getWord(word_th).getWord_explain().trim());
    }//GEN-LAST:event_wordListKeyTyped

    private void wordListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordListKeyReleased
        // TODO add your handling code here:
        String word = wordList.getSelectedValue();
        int word_th = wordList.getSelectedIndex();
        word_target.setText(word);
        word_type.setText(Dictionary.getWord(word_th).getWord_type().trim());
        word_pronoun.setText(Dictionary.getWord(word_th).getSpell().trim());
        explainArea.setText(Dictionary.getWord(word_th).getWord_explain().trim());
    }//GEN-LAST:event_wordListKeyReleased

    private void playSoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playSoundMouseClicked
        // TODO add your handling code here:
        speech(word_target.getText());
    }//GEN-LAST:event_playSoundMouseClicked

    private void suggestPopupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestPopupMouseClicked
        // TODO add your handling code here:
        /*
        for (int i = 0; i < suggestPopup.getComponentCount(); i++) {
            if (suggestPopup.getComponent(i).isFocusOwner()) {
                String target = suggestPopup.getComponent(i).getName();
                //String explain =
                showTarget.setText(target);
                //showExplain.setText(explain);
                showWord.setVisible(true);
                backButton.setVisible(true);
                menuPanel.setVisible(false);
            }
        } */

        System.out.println("hihihi");

    }//GEN-LAST:event_suggestPopupMouseClicked

    private void playSound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playSound1MouseClicked
        // TODO add your handling code here:
        speech(word_target1.getText());
    }//GEN-LAST:event_playSound1MouseClicked

    private void popupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            int word_th = popupList.getSelectedIndex();
            ArrayList<Word> lookup = ListsuggestWord(wordTarget.getText());
            wordTarget.setText(popupList.getSelectedValue());
            word_target1.setText(popupList.getSelectedValue());
            word_type1.setText(lookup.get(word_th).getWord_type().trim());
            word_pronoun1.setText(lookup.get(word_th).getSpell().trim());
            explainArea1.setText(lookup.get(word_th).getWord_explain().trim());
                    
            showWord.setVisible(true);
            backButton.setVisible(true);
            menuPanel.setVisible(false);
            suggestPopup.setVisible(false);
        }
    }//GEN-LAST:event_popupListMouseClicked

    private void paraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraButtonMouseClicked
        // TODO add your handling code here:
        workingPanel.setVisible(false);
        paraPanel.setVisible(true);
        backButton.setVisible(true);
        //workingPanel3.setVisible(true);
    }//GEN-LAST:event_paraButtonMouseClicked

    private void paraTargetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paraTargetKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                paraExplain.setText(Translator.text_translate(paraTarget.getText()));
            } catch (IOException ex) {
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_paraTargetKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            jLabel9.setText(DictionaryManagement.dictionaryFix(addTarget1.getText(), addType1.getText(), addExplain1.getText(), addSpell1.getText()));
            DictionaryManagement.dictionaryFix(addTarget1.getText(), addType1.getText(), addExplain1.getText(), addSpell1.getText());
            
            //jDialog1.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addType1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addType1FocusGained
        // TODO add your handling code here:
        if (addType1.getText().equals("Nhập từ loại mới")) addType1.setText("");
        addType1.setForeground(Color.BLACK);
    }//GEN-LAST:event_addType1FocusGained

    private void addType1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addType1FocusLost
        // TODO add your handling code here:
        if (!addType1.isFocusOwner() && addType1.getText().trim().equals("")) {
            addType1.setText("Nhập từ loại mới");
            if (addType1.getText().equals("Nhập từ loại mới")) addType1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addType1FocusLost

    private void addSpell1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSpell1FocusGained
        // TODO add your handling code here:
        if (addSpell1.getText().equals("Nhập phát âm mới")) addSpell1.setText("");
        addSpell1.setForeground(Color.BLACK);
    }//GEN-LAST:event_addSpell1FocusGained

    private void addSpell1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addSpell1FocusLost
        // TODO add your handling code here:
        if (!addSpell1.isFocusOwner() && addSpell1.getText().trim().equals("")) {
            addSpell1.setText("Nhập phát âm mới");
            if (addSpell1.getText().equals("Nhập phát âm mới")) addSpell1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addSpell1FocusLost

    private void addTarget1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTarget1FocusGained
        // TODO add your handling code here:
        if (addTarget1.getText().equals("Nhập từ bạn muốn sửa")) addTarget1.setText("");
        addTarget1.setForeground(Color.BLACK);
    }//GEN-LAST:event_addTarget1FocusGained

    private void addTarget1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTarget1FocusLost
        // TODO add your handling code here:
        if (!addTarget1.isFocusOwner() && addTarget1.getText().trim().equals("")) {
            addTarget1.setText("Nhập từ bạn muốn sửa");
            if (addTarget1.getText().equals("Nhập từ bạn muốn sửa")) addTarget1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addTarget1FocusLost

    private void addExplain1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addExplain1FocusGained
        // TODO add your handling code here:
        if (addExplain1.getText().equals("Nghĩa tiếng Việt mới:")) addExplain1.setText("");
        addExplain1.setForeground(Color.BLACK);
    }//GEN-LAST:event_addExplain1FocusGained

    private void addExplain1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addExplain1FocusLost
        // TODO add your handling code here:
        if (!addExplain1.isFocusOwner() && addExplain1.getText().trim().equals("")) {
            addExplain1.setText("Nghĩa tiếng Việt mới:");
            if (addExplain1.getText().equals("Nghĩa tiếng Việt mới:")) addExplain1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_addExplain1FocusLost

    private void addTarget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTarget1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTarget1ActionPerformed

    private void addTargetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTargetMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) addTarget.setText("");
        jLabel5.setText(" ");
    }//GEN-LAST:event_addTargetMouseClicked

    private void paraTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paraTargetActionPerformed

    private void editWPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editWPanelMouseClicked
        // TODO add your handling code here:
        jLabel9.setText(" ");
    }//GEN-LAST:event_editWPanelMouseClicked

    private void addTarget1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTarget1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) addTarget1.setText("");
        jLabel9.setText(" ");
    }//GEN-LAST:event_addTarget1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void runApp() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MyFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addExplain;
    private javax.swing.JTextArea addExplain1;
    private javax.swing.JPanel addPanel;
    private javax.swing.JTextField addSpell;
    private javax.swing.JTextField addSpell1;
    private javax.swing.JTextField addTarget;
    private javax.swing.JTextField addTarget1;
    private javax.swing.JTextField addType;
    private javax.swing.JTextField addType1;
    private javax.swing.JLabel backButton;
    private javax.swing.JPanel constantPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteDic;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel editWPanel;
    private javax.swing.JTabbedPane editdataPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextArea explainArea;
    private javax.swing.JTextArea explainArea1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel nameDictionary;
    private javax.swing.JButton newButton;
    private javax.swing.JButton paraButton;
    private javax.swing.JTextArea paraExplain;
    private javax.swing.JPanel paraPanel;
    private javax.swing.JTextField paraTarget;
    private javax.swing.JLabel playSound;
    private javax.swing.JLabel playSound1;
    private javax.swing.JList<String> popupList;
    private javax.swing.JPanel popupPanel;
    private javax.swing.JPanel removePanel;
    private javax.swing.JLabel searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel showWord;
    private javax.swing.JButton showallButton;
    private javax.swing.JPanel showallPanel;
    private javax.swing.JPopupMenu suggestPopup;
    private javax.swing.JList<String> wordList;
    private javax.swing.JTextField wordTarget;
    private javax.swing.JLabel word_pronoun;
    private javax.swing.JLabel word_pronoun1;
    private javax.swing.JLabel word_target;
    private javax.swing.JLabel word_target1;
    private javax.swing.JLabel word_type;
    private javax.swing.JLabel word_type1;
    private javax.swing.JPanel workingPanel;
    private javax.swing.JPanel workingPanel3;
    private javax.swing.JPanel workingPanel4;
    // End of variables declaration//GEN-END:variables
}
